AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - ./**/Vagrantfile

Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/FileName:
  Enabled: false

