source 'https://supermarket.chef.io'

metadata

cookbook 'openvpn', git: 'https://github.com/xxmitsu/en_ovpn.git', rel: 'cookbooks/openvpn'
cookbook 'chef-solo-search', git: 'https://github.com/xxmitsu/en_ovpn.git', rel: 'cookbooks/chef-solo-search'
